// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using infrastructure;

#nullable disable

namespace infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241116152146_AddParkingSlotTable")]
    partial class AddParkingSlotTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("domain.entities.ParkingSlot", b =>
                {
                    b.Property<int>("ParkingSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParkingSlotId"));

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("OccupiedFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OccupiedUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("SlotNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ParkingSlotId");

                    b.ToTable("ParkingSlots");

                    b.HasData(
                        new
                        {
                            ParkingSlotId = 1,
                            IsOccupied = false,
                            SlotNumber = "Slot-001"
                        },
                        new
                        {
                            ParkingSlotId = 2,
                            IsOccupied = false,
                            SlotNumber = "Slot-002"
                        },
                        new
                        {
                            ParkingSlotId = 3,
                            IsOccupied = false,
                            SlotNumber = "Slot-003"
                        },
                        new
                        {
                            ParkingSlotId = 4,
                            IsOccupied = false,
                            SlotNumber = "Slot-004"
                        },
                        new
                        {
                            ParkingSlotId = 5,
                            IsOccupied = false,
                            SlotNumber = "Slot-005"
                        },
                        new
                        {
                            ParkingSlotId = 6,
                            IsOccupied = false,
                            SlotNumber = "Slot-006"
                        },
                        new
                        {
                            ParkingSlotId = 7,
                            IsOccupied = false,
                            SlotNumber = "Slot-007"
                        },
                        new
                        {
                            ParkingSlotId = 8,
                            IsOccupied = false,
                            SlotNumber = "Slot-008"
                        },
                        new
                        {
                            ParkingSlotId = 9,
                            IsOccupied = false,
                            SlotNumber = "Slot-009"
                        },
                        new
                        {
                            ParkingSlotId = 10,
                            IsOccupied = false,
                            SlotNumber = "Slot-010"
                        },
                        new
                        {
                            ParkingSlotId = 11,
                            IsOccupied = false,
                            SlotNumber = "Slot-011"
                        },
                        new
                        {
                            ParkingSlotId = 12,
                            IsOccupied = false,
                            SlotNumber = "Slot-012"
                        },
                        new
                        {
                            ParkingSlotId = 13,
                            IsOccupied = false,
                            SlotNumber = "Slot-013"
                        },
                        new
                        {
                            ParkingSlotId = 14,
                            IsOccupied = false,
                            SlotNumber = "Slot-014"
                        },
                        new
                        {
                            ParkingSlotId = 15,
                            IsOccupied = false,
                            SlotNumber = "Slot-015"
                        },
                        new
                        {
                            ParkingSlotId = 16,
                            IsOccupied = false,
                            SlotNumber = "Slot-016"
                        },
                        new
                        {
                            ParkingSlotId = 17,
                            IsOccupied = false,
                            SlotNumber = "Slot-017"
                        },
                        new
                        {
                            ParkingSlotId = 18,
                            IsOccupied = false,
                            SlotNumber = "Slot-018"
                        },
                        new
                        {
                            ParkingSlotId = 19,
                            IsOccupied = false,
                            SlotNumber = "Slot-019"
                        },
                        new
                        {
                            ParkingSlotId = 20,
                            IsOccupied = false,
                            SlotNumber = "Slot-020"
                        },
                        new
                        {
                            ParkingSlotId = 21,
                            IsOccupied = false,
                            SlotNumber = "Slot-021"
                        },
                        new
                        {
                            ParkingSlotId = 22,
                            IsOccupied = false,
                            SlotNumber = "Slot-022"
                        },
                        new
                        {
                            ParkingSlotId = 23,
                            IsOccupied = false,
                            SlotNumber = "Slot-023"
                        },
                        new
                        {
                            ParkingSlotId = 24,
                            IsOccupied = false,
                            SlotNumber = "Slot-024"
                        },
                        new
                        {
                            ParkingSlotId = 25,
                            IsOccupied = false,
                            SlotNumber = "Slot-025"
                        },
                        new
                        {
                            ParkingSlotId = 26,
                            IsOccupied = false,
                            SlotNumber = "Slot-026"
                        },
                        new
                        {
                            ParkingSlotId = 27,
                            IsOccupied = false,
                            SlotNumber = "Slot-027"
                        },
                        new
                        {
                            ParkingSlotId = 28,
                            IsOccupied = false,
                            SlotNumber = "Slot-028"
                        },
                        new
                        {
                            ParkingSlotId = 29,
                            IsOccupied = false,
                            SlotNumber = "Slot-029"
                        },
                        new
                        {
                            ParkingSlotId = 30,
                            IsOccupied = false,
                            SlotNumber = "Slot-030"
                        },
                        new
                        {
                            ParkingSlotId = 31,
                            IsOccupied = false,
                            SlotNumber = "Slot-031"
                        },
                        new
                        {
                            ParkingSlotId = 32,
                            IsOccupied = false,
                            SlotNumber = "Slot-032"
                        },
                        new
                        {
                            ParkingSlotId = 33,
                            IsOccupied = false,
                            SlotNumber = "Slot-033"
                        },
                        new
                        {
                            ParkingSlotId = 34,
                            IsOccupied = false,
                            SlotNumber = "Slot-034"
                        },
                        new
                        {
                            ParkingSlotId = 35,
                            IsOccupied = false,
                            SlotNumber = "Slot-035"
                        },
                        new
                        {
                            ParkingSlotId = 36,
                            IsOccupied = false,
                            SlotNumber = "Slot-036"
                        },
                        new
                        {
                            ParkingSlotId = 37,
                            IsOccupied = false,
                            SlotNumber = "Slot-037"
                        },
                        new
                        {
                            ParkingSlotId = 38,
                            IsOccupied = false,
                            SlotNumber = "Slot-038"
                        },
                        new
                        {
                            ParkingSlotId = 39,
                            IsOccupied = false,
                            SlotNumber = "Slot-039"
                        },
                        new
                        {
                            ParkingSlotId = 40,
                            IsOccupied = false,
                            SlotNumber = "Slot-040"
                        },
                        new
                        {
                            ParkingSlotId = 41,
                            IsOccupied = false,
                            SlotNumber = "Slot-041"
                        },
                        new
                        {
                            ParkingSlotId = 42,
                            IsOccupied = false,
                            SlotNumber = "Slot-042"
                        },
                        new
                        {
                            ParkingSlotId = 43,
                            IsOccupied = false,
                            SlotNumber = "Slot-043"
                        },
                        new
                        {
                            ParkingSlotId = 44,
                            IsOccupied = false,
                            SlotNumber = "Slot-044"
                        },
                        new
                        {
                            ParkingSlotId = 45,
                            IsOccupied = false,
                            SlotNumber = "Slot-045"
                        },
                        new
                        {
                            ParkingSlotId = 46,
                            IsOccupied = false,
                            SlotNumber = "Slot-046"
                        },
                        new
                        {
                            ParkingSlotId = 47,
                            IsOccupied = false,
                            SlotNumber = "Slot-047"
                        },
                        new
                        {
                            ParkingSlotId = 48,
                            IsOccupied = false,
                            SlotNumber = "Slot-048"
                        },
                        new
                        {
                            ParkingSlotId = 49,
                            IsOccupied = false,
                            SlotNumber = "Slot-049"
                        },
                        new
                        {
                            ParkingSlotId = 50,
                            IsOccupied = false,
                            SlotNumber = "Slot-050"
                        },
                        new
                        {
                            ParkingSlotId = 51,
                            IsOccupied = false,
                            SlotNumber = "Slot-051"
                        },
                        new
                        {
                            ParkingSlotId = 52,
                            IsOccupied = false,
                            SlotNumber = "Slot-052"
                        },
                        new
                        {
                            ParkingSlotId = 53,
                            IsOccupied = false,
                            SlotNumber = "Slot-053"
                        },
                        new
                        {
                            ParkingSlotId = 54,
                            IsOccupied = false,
                            SlotNumber = "Slot-054"
                        },
                        new
                        {
                            ParkingSlotId = 55,
                            IsOccupied = false,
                            SlotNumber = "Slot-055"
                        },
                        new
                        {
                            ParkingSlotId = 56,
                            IsOccupied = false,
                            SlotNumber = "Slot-056"
                        },
                        new
                        {
                            ParkingSlotId = 57,
                            IsOccupied = false,
                            SlotNumber = "Slot-057"
                        },
                        new
                        {
                            ParkingSlotId = 58,
                            IsOccupied = false,
                            SlotNumber = "Slot-058"
                        },
                        new
                        {
                            ParkingSlotId = 59,
                            IsOccupied = false,
                            SlotNumber = "Slot-059"
                        },
                        new
                        {
                            ParkingSlotId = 60,
                            IsOccupied = false,
                            SlotNumber = "Slot-060"
                        },
                        new
                        {
                            ParkingSlotId = 61,
                            IsOccupied = false,
                            SlotNumber = "Slot-061"
                        },
                        new
                        {
                            ParkingSlotId = 62,
                            IsOccupied = false,
                            SlotNumber = "Slot-062"
                        },
                        new
                        {
                            ParkingSlotId = 63,
                            IsOccupied = false,
                            SlotNumber = "Slot-063"
                        },
                        new
                        {
                            ParkingSlotId = 64,
                            IsOccupied = false,
                            SlotNumber = "Slot-064"
                        },
                        new
                        {
                            ParkingSlotId = 65,
                            IsOccupied = false,
                            SlotNumber = "Slot-065"
                        },
                        new
                        {
                            ParkingSlotId = 66,
                            IsOccupied = false,
                            SlotNumber = "Slot-066"
                        },
                        new
                        {
                            ParkingSlotId = 67,
                            IsOccupied = false,
                            SlotNumber = "Slot-067"
                        },
                        new
                        {
                            ParkingSlotId = 68,
                            IsOccupied = false,
                            SlotNumber = "Slot-068"
                        },
                        new
                        {
                            ParkingSlotId = 69,
                            IsOccupied = false,
                            SlotNumber = "Slot-069"
                        },
                        new
                        {
                            ParkingSlotId = 70,
                            IsOccupied = false,
                            SlotNumber = "Slot-070"
                        },
                        new
                        {
                            ParkingSlotId = 71,
                            IsOccupied = false,
                            SlotNumber = "Slot-071"
                        },
                        new
                        {
                            ParkingSlotId = 72,
                            IsOccupied = false,
                            SlotNumber = "Slot-072"
                        },
                        new
                        {
                            ParkingSlotId = 73,
                            IsOccupied = false,
                            SlotNumber = "Slot-073"
                        },
                        new
                        {
                            ParkingSlotId = 74,
                            IsOccupied = false,
                            SlotNumber = "Slot-074"
                        },
                        new
                        {
                            ParkingSlotId = 75,
                            IsOccupied = false,
                            SlotNumber = "Slot-075"
                        },
                        new
                        {
                            ParkingSlotId = 76,
                            IsOccupied = false,
                            SlotNumber = "Slot-076"
                        },
                        new
                        {
                            ParkingSlotId = 77,
                            IsOccupied = false,
                            SlotNumber = "Slot-077"
                        },
                        new
                        {
                            ParkingSlotId = 78,
                            IsOccupied = false,
                            SlotNumber = "Slot-078"
                        },
                        new
                        {
                            ParkingSlotId = 79,
                            IsOccupied = false,
                            SlotNumber = "Slot-079"
                        },
                        new
                        {
                            ParkingSlotId = 80,
                            IsOccupied = false,
                            SlotNumber = "Slot-080"
                        },
                        new
                        {
                            ParkingSlotId = 81,
                            IsOccupied = false,
                            SlotNumber = "Slot-081"
                        },
                        new
                        {
                            ParkingSlotId = 82,
                            IsOccupied = false,
                            SlotNumber = "Slot-082"
                        },
                        new
                        {
                            ParkingSlotId = 83,
                            IsOccupied = false,
                            SlotNumber = "Slot-083"
                        },
                        new
                        {
                            ParkingSlotId = 84,
                            IsOccupied = false,
                            SlotNumber = "Slot-084"
                        },
                        new
                        {
                            ParkingSlotId = 85,
                            IsOccupied = false,
                            SlotNumber = "Slot-085"
                        },
                        new
                        {
                            ParkingSlotId = 86,
                            IsOccupied = false,
                            SlotNumber = "Slot-086"
                        },
                        new
                        {
                            ParkingSlotId = 87,
                            IsOccupied = false,
                            SlotNumber = "Slot-087"
                        },
                        new
                        {
                            ParkingSlotId = 88,
                            IsOccupied = false,
                            SlotNumber = "Slot-088"
                        },
                        new
                        {
                            ParkingSlotId = 89,
                            IsOccupied = false,
                            SlotNumber = "Slot-089"
                        },
                        new
                        {
                            ParkingSlotId = 90,
                            IsOccupied = false,
                            SlotNumber = "Slot-090"
                        },
                        new
                        {
                            ParkingSlotId = 91,
                            IsOccupied = false,
                            SlotNumber = "Slot-091"
                        },
                        new
                        {
                            ParkingSlotId = 92,
                            IsOccupied = false,
                            SlotNumber = "Slot-092"
                        },
                        new
                        {
                            ParkingSlotId = 93,
                            IsOccupied = false,
                            SlotNumber = "Slot-093"
                        },
                        new
                        {
                            ParkingSlotId = 94,
                            IsOccupied = false,
                            SlotNumber = "Slot-094"
                        },
                        new
                        {
                            ParkingSlotId = 95,
                            IsOccupied = false,
                            SlotNumber = "Slot-095"
                        },
                        new
                        {
                            ParkingSlotId = 96,
                            IsOccupied = false,
                            SlotNumber = "Slot-096"
                        },
                        new
                        {
                            ParkingSlotId = 97,
                            IsOccupied = false,
                            SlotNumber = "Slot-097"
                        },
                        new
                        {
                            ParkingSlotId = 98,
                            IsOccupied = false,
                            SlotNumber = "Slot-098"
                        },
                        new
                        {
                            ParkingSlotId = 99,
                            IsOccupied = false,
                            SlotNumber = "Slot-099"
                        },
                        new
                        {
                            ParkingSlotId = 100,
                            IsOccupied = false,
                            SlotNumber = "Slot-100"
                        },
                        new
                        {
                            ParkingSlotId = 101,
                            IsOccupied = false,
                            SlotNumber = "Slot-101"
                        },
                        new
                        {
                            ParkingSlotId = 102,
                            IsOccupied = false,
                            SlotNumber = "Slot-102"
                        },
                        new
                        {
                            ParkingSlotId = 103,
                            IsOccupied = false,
                            SlotNumber = "Slot-103"
                        },
                        new
                        {
                            ParkingSlotId = 104,
                            IsOccupied = false,
                            SlotNumber = "Slot-104"
                        },
                        new
                        {
                            ParkingSlotId = 105,
                            IsOccupied = false,
                            SlotNumber = "Slot-105"
                        },
                        new
                        {
                            ParkingSlotId = 106,
                            IsOccupied = false,
                            SlotNumber = "Slot-106"
                        },
                        new
                        {
                            ParkingSlotId = 107,
                            IsOccupied = false,
                            SlotNumber = "Slot-107"
                        },
                        new
                        {
                            ParkingSlotId = 108,
                            IsOccupied = false,
                            SlotNumber = "Slot-108"
                        },
                        new
                        {
                            ParkingSlotId = 109,
                            IsOccupied = false,
                            SlotNumber = "Slot-109"
                        },
                        new
                        {
                            ParkingSlotId = 110,
                            IsOccupied = false,
                            SlotNumber = "Slot-110"
                        },
                        new
                        {
                            ParkingSlotId = 111,
                            IsOccupied = false,
                            SlotNumber = "Slot-111"
                        },
                        new
                        {
                            ParkingSlotId = 112,
                            IsOccupied = false,
                            SlotNumber = "Slot-112"
                        },
                        new
                        {
                            ParkingSlotId = 113,
                            IsOccupied = false,
                            SlotNumber = "Slot-113"
                        },
                        new
                        {
                            ParkingSlotId = 114,
                            IsOccupied = false,
                            SlotNumber = "Slot-114"
                        },
                        new
                        {
                            ParkingSlotId = 115,
                            IsOccupied = false,
                            SlotNumber = "Slot-115"
                        },
                        new
                        {
                            ParkingSlotId = 116,
                            IsOccupied = false,
                            SlotNumber = "Slot-116"
                        },
                        new
                        {
                            ParkingSlotId = 117,
                            IsOccupied = false,
                            SlotNumber = "Slot-117"
                        },
                        new
                        {
                            ParkingSlotId = 118,
                            IsOccupied = false,
                            SlotNumber = "Slot-118"
                        },
                        new
                        {
                            ParkingSlotId = 119,
                            IsOccupied = false,
                            SlotNumber = "Slot-119"
                        },
                        new
                        {
                            ParkingSlotId = 120,
                            IsOccupied = false,
                            SlotNumber = "Slot-120"
                        },
                        new
                        {
                            ParkingSlotId = 121,
                            IsOccupied = false,
                            SlotNumber = "Slot-121"
                        },
                        new
                        {
                            ParkingSlotId = 122,
                            IsOccupied = false,
                            SlotNumber = "Slot-122"
                        },
                        new
                        {
                            ParkingSlotId = 123,
                            IsOccupied = false,
                            SlotNumber = "Slot-123"
                        },
                        new
                        {
                            ParkingSlotId = 124,
                            IsOccupied = false,
                            SlotNumber = "Slot-124"
                        },
                        new
                        {
                            ParkingSlotId = 125,
                            IsOccupied = false,
                            SlotNumber = "Slot-125"
                        },
                        new
                        {
                            ParkingSlotId = 126,
                            IsOccupied = false,
                            SlotNumber = "Slot-126"
                        },
                        new
                        {
                            ParkingSlotId = 127,
                            IsOccupied = false,
                            SlotNumber = "Slot-127"
                        },
                        new
                        {
                            ParkingSlotId = 128,
                            IsOccupied = false,
                            SlotNumber = "Slot-128"
                        },
                        new
                        {
                            ParkingSlotId = 129,
                            IsOccupied = false,
                            SlotNumber = "Slot-129"
                        },
                        new
                        {
                            ParkingSlotId = 130,
                            IsOccupied = false,
                            SlotNumber = "Slot-130"
                        },
                        new
                        {
                            ParkingSlotId = 131,
                            IsOccupied = false,
                            SlotNumber = "Slot-131"
                        },
                        new
                        {
                            ParkingSlotId = 132,
                            IsOccupied = false,
                            SlotNumber = "Slot-132"
                        },
                        new
                        {
                            ParkingSlotId = 133,
                            IsOccupied = false,
                            SlotNumber = "Slot-133"
                        },
                        new
                        {
                            ParkingSlotId = 134,
                            IsOccupied = false,
                            SlotNumber = "Slot-134"
                        },
                        new
                        {
                            ParkingSlotId = 135,
                            IsOccupied = false,
                            SlotNumber = "Slot-135"
                        },
                        new
                        {
                            ParkingSlotId = 136,
                            IsOccupied = false,
                            SlotNumber = "Slot-136"
                        },
                        new
                        {
                            ParkingSlotId = 137,
                            IsOccupied = false,
                            SlotNumber = "Slot-137"
                        },
                        new
                        {
                            ParkingSlotId = 138,
                            IsOccupied = false,
                            SlotNumber = "Slot-138"
                        },
                        new
                        {
                            ParkingSlotId = 139,
                            IsOccupied = false,
                            SlotNumber = "Slot-139"
                        },
                        new
                        {
                            ParkingSlotId = 140,
                            IsOccupied = false,
                            SlotNumber = "Slot-140"
                        },
                        new
                        {
                            ParkingSlotId = 141,
                            IsOccupied = false,
                            SlotNumber = "Slot-141"
                        },
                        new
                        {
                            ParkingSlotId = 142,
                            IsOccupied = false,
                            SlotNumber = "Slot-142"
                        },
                        new
                        {
                            ParkingSlotId = 143,
                            IsOccupied = false,
                            SlotNumber = "Slot-143"
                        },
                        new
                        {
                            ParkingSlotId = 144,
                            IsOccupied = false,
                            SlotNumber = "Slot-144"
                        },
                        new
                        {
                            ParkingSlotId = 145,
                            IsOccupied = false,
                            SlotNumber = "Slot-145"
                        },
                        new
                        {
                            ParkingSlotId = 146,
                            IsOccupied = false,
                            SlotNumber = "Slot-146"
                        },
                        new
                        {
                            ParkingSlotId = 147,
                            IsOccupied = false,
                            SlotNumber = "Slot-147"
                        },
                        new
                        {
                            ParkingSlotId = 148,
                            IsOccupied = false,
                            SlotNumber = "Slot-148"
                        },
                        new
                        {
                            ParkingSlotId = 149,
                            IsOccupied = false,
                            SlotNumber = "Slot-149"
                        },
                        new
                        {
                            ParkingSlotId = 150,
                            IsOccupied = false,
                            SlotNumber = "Slot-150"
                        },
                        new
                        {
                            ParkingSlotId = 151,
                            IsOccupied = false,
                            SlotNumber = "Slot-151"
                        },
                        new
                        {
                            ParkingSlotId = 152,
                            IsOccupied = false,
                            SlotNumber = "Slot-152"
                        },
                        new
                        {
                            ParkingSlotId = 153,
                            IsOccupied = false,
                            SlotNumber = "Slot-153"
                        },
                        new
                        {
                            ParkingSlotId = 154,
                            IsOccupied = false,
                            SlotNumber = "Slot-154"
                        },
                        new
                        {
                            ParkingSlotId = 155,
                            IsOccupied = false,
                            SlotNumber = "Slot-155"
                        },
                        new
                        {
                            ParkingSlotId = 156,
                            IsOccupied = false,
                            SlotNumber = "Slot-156"
                        },
                        new
                        {
                            ParkingSlotId = 157,
                            IsOccupied = false,
                            SlotNumber = "Slot-157"
                        },
                        new
                        {
                            ParkingSlotId = 158,
                            IsOccupied = false,
                            SlotNumber = "Slot-158"
                        },
                        new
                        {
                            ParkingSlotId = 159,
                            IsOccupied = false,
                            SlotNumber = "Slot-159"
                        },
                        new
                        {
                            ParkingSlotId = 160,
                            IsOccupied = false,
                            SlotNumber = "Slot-160"
                        },
                        new
                        {
                            ParkingSlotId = 161,
                            IsOccupied = false,
                            SlotNumber = "Slot-161"
                        },
                        new
                        {
                            ParkingSlotId = 162,
                            IsOccupied = false,
                            SlotNumber = "Slot-162"
                        },
                        new
                        {
                            ParkingSlotId = 163,
                            IsOccupied = false,
                            SlotNumber = "Slot-163"
                        },
                        new
                        {
                            ParkingSlotId = 164,
                            IsOccupied = false,
                            SlotNumber = "Slot-164"
                        },
                        new
                        {
                            ParkingSlotId = 165,
                            IsOccupied = false,
                            SlotNumber = "Slot-165"
                        },
                        new
                        {
                            ParkingSlotId = 166,
                            IsOccupied = false,
                            SlotNumber = "Slot-166"
                        },
                        new
                        {
                            ParkingSlotId = 167,
                            IsOccupied = false,
                            SlotNumber = "Slot-167"
                        },
                        new
                        {
                            ParkingSlotId = 168,
                            IsOccupied = false,
                            SlotNumber = "Slot-168"
                        },
                        new
                        {
                            ParkingSlotId = 169,
                            IsOccupied = false,
                            SlotNumber = "Slot-169"
                        },
                        new
                        {
                            ParkingSlotId = 170,
                            IsOccupied = false,
                            SlotNumber = "Slot-170"
                        },
                        new
                        {
                            ParkingSlotId = 171,
                            IsOccupied = false,
                            SlotNumber = "Slot-171"
                        },
                        new
                        {
                            ParkingSlotId = 172,
                            IsOccupied = false,
                            SlotNumber = "Slot-172"
                        },
                        new
                        {
                            ParkingSlotId = 173,
                            IsOccupied = false,
                            SlotNumber = "Slot-173"
                        },
                        new
                        {
                            ParkingSlotId = 174,
                            IsOccupied = false,
                            SlotNumber = "Slot-174"
                        },
                        new
                        {
                            ParkingSlotId = 175,
                            IsOccupied = false,
                            SlotNumber = "Slot-175"
                        },
                        new
                        {
                            ParkingSlotId = 176,
                            IsOccupied = false,
                            SlotNumber = "Slot-176"
                        },
                        new
                        {
                            ParkingSlotId = 177,
                            IsOccupied = false,
                            SlotNumber = "Slot-177"
                        },
                        new
                        {
                            ParkingSlotId = 178,
                            IsOccupied = false,
                            SlotNumber = "Slot-178"
                        },
                        new
                        {
                            ParkingSlotId = 179,
                            IsOccupied = false,
                            SlotNumber = "Slot-179"
                        },
                        new
                        {
                            ParkingSlotId = 180,
                            IsOccupied = false,
                            SlotNumber = "Slot-180"
                        },
                        new
                        {
                            ParkingSlotId = 181,
                            IsOccupied = false,
                            SlotNumber = "Slot-181"
                        },
                        new
                        {
                            ParkingSlotId = 182,
                            IsOccupied = false,
                            SlotNumber = "Slot-182"
                        },
                        new
                        {
                            ParkingSlotId = 183,
                            IsOccupied = false,
                            SlotNumber = "Slot-183"
                        },
                        new
                        {
                            ParkingSlotId = 184,
                            IsOccupied = false,
                            SlotNumber = "Slot-184"
                        },
                        new
                        {
                            ParkingSlotId = 185,
                            IsOccupied = false,
                            SlotNumber = "Slot-185"
                        },
                        new
                        {
                            ParkingSlotId = 186,
                            IsOccupied = false,
                            SlotNumber = "Slot-186"
                        },
                        new
                        {
                            ParkingSlotId = 187,
                            IsOccupied = false,
                            SlotNumber = "Slot-187"
                        },
                        new
                        {
                            ParkingSlotId = 188,
                            IsOccupied = false,
                            SlotNumber = "Slot-188"
                        },
                        new
                        {
                            ParkingSlotId = 189,
                            IsOccupied = false,
                            SlotNumber = "Slot-189"
                        },
                        new
                        {
                            ParkingSlotId = 190,
                            IsOccupied = false,
                            SlotNumber = "Slot-190"
                        },
                        new
                        {
                            ParkingSlotId = 191,
                            IsOccupied = false,
                            SlotNumber = "Slot-191"
                        },
                        new
                        {
                            ParkingSlotId = 192,
                            IsOccupied = false,
                            SlotNumber = "Slot-192"
                        },
                        new
                        {
                            ParkingSlotId = 193,
                            IsOccupied = false,
                            SlotNumber = "Slot-193"
                        },
                        new
                        {
                            ParkingSlotId = 194,
                            IsOccupied = false,
                            SlotNumber = "Slot-194"
                        },
                        new
                        {
                            ParkingSlotId = 195,
                            IsOccupied = false,
                            SlotNumber = "Slot-195"
                        },
                        new
                        {
                            ParkingSlotId = 196,
                            IsOccupied = false,
                            SlotNumber = "Slot-196"
                        },
                        new
                        {
                            ParkingSlotId = 197,
                            IsOccupied = false,
                            SlotNumber = "Slot-197"
                        },
                        new
                        {
                            ParkingSlotId = 198,
                            IsOccupied = false,
                            SlotNumber = "Slot-198"
                        },
                        new
                        {
                            ParkingSlotId = 199,
                            IsOccupied = false,
                            SlotNumber = "Slot-199"
                        },
                        new
                        {
                            ParkingSlotId = 200,
                            IsOccupied = false,
                            SlotNumber = "Slot-200"
                        });
                });

            modelBuilder.Entity("domain.entities.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExitTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OwnerAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OwnerPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("ParkingCharge")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("ParkingSlotId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleId");

                    b.HasIndex("LicenseNumber")
                        .IsUnique();

                    b.HasIndex("ParkingSlotId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("domain.entities.Vehicle", b =>
                {
                    b.HasOne("domain.entities.ParkingSlot", "ParkingSlot")
                        .WithMany()
                        .HasForeignKey("ParkingSlotId");

                    b.Navigation("ParkingSlot");
                });
#pragma warning restore 612, 618
        }
    }
}
